// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kegbvaikqelwezpehlhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlZ2J2YWlrcWVsd2V6cGVobGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2NDc4MzUsImV4cCI6MjA4NzIyMzgzNX0.hIRjDR4D6p8RAsnWMhkF1stRDr_oa0yMsqukCPADyh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper function to inject the JWT to all future supabase requests
export const setAuthToken = (token: string | null) => {
  if (token) {
    supabase.realtime.setAuth(token);
    // Para as requisições normais (REST), definimos o header globalmente
    // @ts-ignore - Supabase JS allows overriding headers on the fly via global config
    supabase.rest.headers['Authorization'] = `Bearer ${token}`;
  } else {
    // @ts-ignore
    delete supabase.rest.headers['Authorization'];
  }
};